#
# Component Makefile
#

ifdef CONFIG_AUDIO_MAD
CFLAGS += -DCONFIG_AUDIO_MAD
COMPONENT_SRCDIRS += mad
COMPONENT_ADD_INCLUDEDIRS += mad/include
endif


ifdef CONFIG_AUDIO_HELIX
CFLAGS += -DARM -DCONFIG_AUDIO_HELIX
COMPONENT_SRCDIRS += helix
COMPONENT_ADD_INCLUDEDIRS += helix/include
endif